version: '3'                                                 
services:
  container_v1:                    
    image: "v1:latest"
    ports:                     
      - "7000:8000"               
  container_v2:      
    image: "v2:latest"         
    ports:
      - "8000:8000"               
  nginx:
    image: "nginx:latest"   
    ports:
      - "9000:80"            
    volumes: 
      - ./loadbalancer.conf:/etc/nginx/conf.d/default.conf:ro

